# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      

      # Note: This workflow uses the latest stable version of the Dart SDK.
      # You can specify other versions if desired, see documentation here:
      # https://github.com/dart-lang/setup-dart/blob/main/README.md
      - uses: dart-lang/setup-dart@v1
      # - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
        with:
          sdk: "3.2.0"


      - name: Fetch all commit info from main repo & save it in target-repo/commits.log
        id: fetch_all_commits
        run: |
          mkdir -p target-repo  # Ensure target-repo directory exists
          git -C target-repo log --all --graph --decorate --pretty=format:"%s|%cd" > target-repo/commits.log
          ls -l target-repo  # Verify contents of target-repo
          cat target-repo/commits.log  # Debugging output to verify contents
